--- # Site configuration
entries:
    layout: default.twig

# Files to skip - list of preg expressions is expected
skip: [/\.swp$/, /\.bak$/, /.DS_Store/]

# Folders and files to copy without processing
# Note that `media` will be copied regardless of this option,
# as long as we don't want to break BC (v0.6 ?)
copy: [media, favicon.ico]
